//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiplexBookingWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING
    {
        public int BookingID { get; set; }
        public Nullable<int> ShowID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> BookedDate { get; set; }
        public Nullable<System.DateTime> ShowDate { get; set; }
        public Nullable<int> No_of_Seats { get; set; }
        public string Seat_type_Desc { get; set; }
    
        public virtual SHOW SHOW { get; set; }
        public virtual USER USER { get; set; }
    }
}
