//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiplexBookingWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HALL_CAPACITY
    {
        public int HallNo { get; set; }
        public Nullable<int> HallID { get; set; }
        public string SeatType { get; set; }
        public Nullable<int> SeatCount { get; set; }
        public Nullable<double> SeatFare { get; set; }
    
        public virtual HALL HALL { get; set; }
    }
}
