//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiplexBookingWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MOVIEDBEntities : DbContext
    {
        public MOVIEDBEntities()
            : base("name=MOVIEDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOOKING> BOOKINGs { get; set; }
        public virtual DbSet<FEEDBACK> FEEDBACKs { get; set; }
        public virtual DbSet<FOOD> FOODs { get; set; }
        public virtual DbSet<HALL> HALLs { get; set; }
        public virtual DbSet<HALL_CAPACITY> HALL_CAPACITY { get; set; }
        public virtual DbSet<MAGAZINE> MAGAZINEs { get; set; }
        public virtual DbSet<MOVIE> MOVIEs { get; set; }
        public virtual DbSet<SHOW> SHOWs { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
    }
}
